# Generated by Django 6.0 on 2025-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapillaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='money_devolution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='operation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
