# Generated by Django 6.0 on 2025-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapillaves', '0002_operation_money_devolution_operation_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
