# Generated by Django 6.0 on 2025-12-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapillaves', '0004_operation_product_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='money_devolution',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='product_replacement',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
