# Generated by Django 6.0 on 2025-12-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapillaves', '0005_alter_operation_money_devolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
