# Generated by Django 6.0 on 2025-12-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapillaves', '0003_alter_operation_quantity_alter_operation_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='product_replacement',
            field=models.BooleanField(default=False),
        ),
    ]
